"""make children birthday not nullable

Revision ID: 845bbe560611
Revises: b870b0bc694c
Create Date: 2026-06-01 15:51:39.484449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845bbe560611'
down_revision: Union[str, Sequence[str], None] = 'b870b0bc694c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('children', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('children', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
